version: '1.0'

services:
  trailstore.host:
    image: ${DOCKER_REGISTRY-}trailstore
    container_name: trailstore.host
    environment:
      - ConnectionStrings__DefaultConnection=Host=trailstore.database;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5297:8080"
    depends_on:
      - trailstore.database
        
  trailstore.database:
    image: postgres:16
    container_name: trailstore.database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - trailstore-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
        
volumes:
  trailstore-pgdata: